#!/usr/bin/env python

# Written by Dong Yuan Yang (dyan263)

import os
import sys
import re
from shutil import copyfile


def sorty(arr):
    def con(text): return int(text) if text.isdigit() else text

    def alphanum(key): return [con(c) for c in re.split('([0-9]+)', key)]
    return sorted(arr, key=alphanum)


def main(*argv):
    if len(argv) != 2:
        print "Incorrect number of arguments"
        return

    path = os.getcwd() + "/.versiondir"
    files = os.listdir(path)
    filearr = []
    for i in files:
        spl = i.split(".")
        if len(spl) == 3:
            fn = spl[0] + "." + spl[1]
        elif len(spl) == 2:
            fn = spl[0]
        else:
            print "you've messed up"
        if fn == argv[0]:
            filearr.append(i)

    filearr = sorty(filearr)
    filearr.reverse()

    tobefirst = argv[0] + "." + argv[1]
    tobefirstpath = path + "/" + tobefirst

    if os.path.exists(tobefirstpath):
        tempStr = argv[0] + ".t"
        tempStrPath = path + "/" + tempStr
        copyfile(tobefirstpath, tempStrPath)
    else:
        print "Version does not exist"
        return

    verVals = ["1", "2", "3", "4", "5"]
    if len(filearr) > 1:

        for i in filearr:
            spl = i.split(".")
            if len(spl) == 3:
                if spl[2] in verVals:
                    newVal = int(spl[2])+1
                    spl = spl[:2]
                    spl.append(str(newVal))
                    newer = ".".join(spl)
                    oldy = path + "/" + i
                    newly = path + "/" + newer
                    os.rename(oldy, newly)
            elif len(spl) == 2:
                if spl[1] in verVals:
                    newVal = int(spl[1])+1
                    spl = spl[:1]
                    spl.append(str(newVal))
                    newer = ".".join(spl)
                    oldy = path + "/" + i
                    newly = path + "/" + newer
                    os.rename(oldy, newly)
            else:
                print "You've entered some pretty messed up file name, please why are you trying to screw me over"
        prevFirstPath = path + "/" + argv[0] + ".1"
        os.rename(tempStrPath, prevFirstPath)

    else:
        os.remove(tempStrPath)

    print "Current version is now", argv[1]


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
